general:
  collectTelemetryData: false
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      apiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com/'
      org: '4a1117f3trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
