general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'e97a1146trial_e97a1146trial'
      space: 'Lokesh'
      credentialsId: 'btp'
