general:
  collectTelemetryData: false
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      apiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com/'
      org: 'e97a1146trial_e97a1146trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
