general:
steps:
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    cloudFoundry:
        cfApiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
        cfOrg: 'e97a1146trial_e97a1146trial'
        space: 'Lokesh'
        credentialId: 'cfCredentialsId'
