general:
  steps:
    mtaBuild:
      buildTarget: 'CF'
    cloudFoundryDeploy:
      deployTool: 'mtaDeployPlugin'
      deployType: 'standard'
      cfApiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
      cfOrg: 'e97a1146trial_e97a1146trial'
      cloudFoundry:
        space: 'Lokesh'
        username: 'lokesh.b.2020.ad@ritchennai.edu.in'
        password: {
          credentialId: 'cfCredentialsId'
        }
