general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    cloudFoundry:
        Endpoint: 'https://api.cf.us10-001.hana.ondemand.com'
        Org: '8e581cbf-4802-42c1-ab67-d689727bd349'
        Space: 'Lokesh'
        Username: 'lokesh.b.2020.ad@ritchennai.edu.in'
        Password:
          credentialId: 'cfCredentialsId'
